version: '3.8'

# Runs the hozana v2 backend (Symfony)
#
# Usage: `docker-compose up` then open http://hozana.local:1819/api/fr/communities

services:
  php-api:
    environment:
      - "HOZANA_E2E_DB_URL=mysql://hozana:hozana@db:3306/hozana_e2e"
    volumes:
      - ./backend:/data/code:delegated
    env_file: ./backend/.env.dev
